// Bilingual copy. Add a new language by adding another top-level key.
window.COPY = {
  ko: {
    nav: { programs: 'Programs', about: 'About', partners: 'Partners', stories: 'Stories', news: 'News', apply: '지원하기' },
    hero: {
      kicker: '글로벌 청년 교육 이니셔티브',
      title_l1: '170개국의 스카우트,',
      title_l2: '하나의 학습 경로로.',
      sub: 'DreamPath는 전 세계 스카우트 청년을 한국의 고등교육으로 연결합니다. 온라인으로, 합리적인 비용으로, 이미 신뢰받는 네트워크 위에서.',
      cta1: '프로그램 둘러보기',
      cta2: '어떻게 작동하나요',
    },
    stats: [
      { n: '170+', l: '국가의 스카우트 네트워크' },
      { n: '57M', l: '전 세계 스카우트 멤버' },
      { n: '1', l: '첫 파트너 기관 · CUFS' },
      { n: '5', l: '운영 중인 마이크로디그리' },
    ],
    how: {
      kicker: 'HOW IT WORKS',
      title: '기존 네트워크를 학습자 파이프라인으로.',
      steps: [
        { n: '01', t: '스카우트 지도자가 학습자를 추천합니다', d: '국가별 스카우트 조직이 검증한 학습자만 지원할 수 있습니다.' },
        { n: '02', t: '프로그램을 선택하고 지원서를 제출합니다', d: '마이크로디그리, 온라인 학위, 어학 트랙 중에서 선택할 수 있습니다.' },
        { n: '03', t: '파트너 대학에서 학습이 시작됩니다', d: '첫 파트너는 사이버한국외국어대학교(CUFS). 100% 온라인.' },
      ],
    },
    programs: {
      kicker: 'PROGRAMS',
      title: '5개의 CUFS 마이크로디그리. 모두 온라인.',
      sub: 'AI, 스토리텔링, 유튜브, K-뷰티, 비즈니스 한국어까지 글로벌 학습자를 위한 5개 과정을 확인하세요.',
    },
    partners: {
      kicker: 'PARTNERS',
      title: '신뢰받는 네트워크 위에서.',
      sub: 'DreamPath는 파트너 교육기관, 글로벌 스카우트 조직, 후원 기관과 함께 운영됩니다.',
    },
    stories: {
      kicker: 'STORIES',
      title: '먼저 걸어간 사람들.',
    },
    cta_banner: {
      title: '당신의 다음 학기를 여기에서.',
      sub: '2025년 가을 학기 지원이 열려있습니다.',
      cta: '지금 지원하기',
    },
  },
  en: {
    nav: { programs: 'Programs', about: 'About', partners: 'Partners', stories: 'Stories', news: 'News', apply: 'Apply' },
    hero: {
      kicker: 'A GLOBAL YOUTH EDUCATION INITIATIVE',
      title_l1: 'One learning path,',
      title_l2: '170 countries of scouts.',
      sub: 'DreamPath connects global scouting youth to Korean higher education — online, affordable, and built on the trust of a network that already exists.',
      cta1: 'Explore programs',
      cta2: 'How it works',
    },
    stats: [
      { n: '170+', l: 'Countries in the scout network' },
      { n: '57M', l: 'Scout members worldwide' },
      { n: '1', l: 'First partner · CUFS' },
      { n: '5', l: 'Micro-degrees live' },
    ],
    how: {
      kicker: 'HOW IT WORKS',
      title: 'Turning an existing network into a learner pipeline.',
      steps: [
        { n: '01', t: 'A scout leader nominates the learner', d: 'Only learners vetted by their national scout organization can apply.' },
        { n: '02', t: 'Choose a program and submit', d: 'Pick from micro-degrees, full online degrees, or language tracks.' },
        { n: '03', t: 'Learning begins at the partner university', d: 'First partner is Cyber Hankuk University of Foreign Studies. 100% online.' },
      ],
    },
    programs: {
      kicker: 'PROGRAMS',
      title: 'Five CUFS micro-degrees. All online.',
      sub: 'Explore five tracks for global learners in AI, storytelling, YouTube, K-beauty, and business Korean.',
    },
    partners: {
      kicker: 'PARTNERS',
      title: 'Built on a trusted network.',
      sub: 'DreamPath operates with partner universities, global scout organizations, and supporting institutions.',
    },
    stories: {
      kicker: 'STORIES',
      title: 'People who walked the path first.',
    },
    cta_banner: {
      title: 'Your next semester starts here.',
      sub: 'Fall 2025 applications are now open.',
      cta: 'Apply now',
    },
  },
};

window.PROGRAMS = [
  {
    id: 'ai-language',
    kicker: 'MICRO-DEGREE · CUFS',
    title_ko: 'AI와 언어교육',
    title_en: 'AI & Language',
    sub_ko: 'AI 기반 영어교육, 언어학, 커뮤니케이션, 빅데이터를 연결하는 1년형 마이크로디그리입니다.',
    sub_en: 'A one-year micro-degree connecting AI-powered language education, linguistics, communication, and big data.',
    meta: ['~1 year', '100% online', 'EN / KO support'],
    level: 'Intermediate',
    status: 'open',
    color: '#1565C0',
    accent: '#42A5F5',
    icon: 'languages',
  },
  {
    id: 'media-content-storytelling',
    kicker: 'MICRO-DEGREE · CUFS',
    title_ko: '미디어 콘텐츠 스토리텔링',
    title_en: 'Media Content Storytelling',
    sub_ko: '역사, 리더십, 커뮤니케이션, 스피치를 통해 글로벌 무대용 스토리텔링 역량을 키웁니다.',
    sub_en: 'Build storytelling power for global stages through history, leadership, communication, and speech.',
    meta: ['~1 year', '100% online', 'EN / KO support'],
    level: 'All Levels',
    status: 'open',
    color: '#7B1FA2',
    accent: '#CE93D8',
    icon: 'mic',
  },
  {
    id: 'youtube-master',
    kicker: 'MICRO-DEGREE · CUFS',
    title_ko: '유튜브 마스터',
    title_en: 'YouTube Master',
    sub_ko: '채널 기획부터 촬영, 편집, 수익화까지 실제 유튜브 채널을 만드는 과정입니다.',
    sub_en: 'Go from channel strategy to shooting, editing, and monetization while building a live YouTube channel.',
    meta: ['~1 year', '100% online', 'EN / KO support'],
    level: 'Beginner',
    status: 'open',
    color: '#C62828',
    accent: '#EF5350',
    icon: 'video',
  },
  {
    id: 'k-beauty-styling',
    kicker: 'MICRO-DEGREE · CUFS',
    title_ko: '기초 K-뷰티 스타일링',
    title_en: 'Basic K-Beauty Styling',
    sub_ko: '색채, 네일, 피부관리, 메이크업을 한 번에 배우는 K-뷰티 입문 트랙입니다.',
    sub_en: 'An entry-level K-beauty track covering color, nails, skincare, and makeup in one program.',
    meta: ['~1 year', '100% online', 'EN / KO support'],
    level: 'Beginner',
    status: 'open',
    color: '#AD1457',
    accent: '#F06292',
    icon: 'sparkles',
  },
  {
    id: 'business-korean',
    kicker: 'MICRO-DEGREE · CUFS',
    title_ko: '비즈니스 한국어',
    title_en: 'Business Korean',
    sub_ko: '입문부터 발표·협상까지, 한국 기업 환경에 맞춘 실전 한국어를 집중적으로 익힙니다.',
    sub_en: 'Move from beginner foundations to presentations and negotiations in Korean business contexts.',
    meta: ['~1 year', '100% online', 'EN / KO support'],
    level: 'Beginner',
    status: 'open',
    color: '#00695C',
    accent: '#4DB6AC',
    icon: 'briefcase',
  },
];

window.PARTNERS = [
  { name: 'CUFS', full: '사이버한국외국어대학교', role_ko: '첫 파트너 · 교육기관', role_en: 'First partner · University', color: '#1E1654' },
  { name: 'WOSM', full: 'World Organization of the Scout Movement', role_ko: '글로벌 네트워크', role_en: 'Global network', color: '#6B2DBE' },
  { name: 'APR', full: 'Asia-Pacific Region Scout', role_ko: '지역 네트워크', role_en: 'Regional network', color: '#0094B4' },
  { name: 'NSOs', full: 'National Scout Organizations', role_ko: '국가별 추천 기관', role_en: 'National endorsement', color: '#248737' },
];

window.STORIES = [
  { tag: 'Kenya', tag_color: '#FF5655', name: 'Amina K.', program: 'Korean Studies',
    quote_ko: '스카우트에서 만난 멘토 덕분에 DreamPath를 알게 됐어요. 지금은 한국어로 일기를 씁니다.',
    quote_en: 'A mentor I met in scouts told me about DreamPath. Now I write my journal in Korean.' },
  { tag: 'Philippines', tag_color: '#0094B4', name: 'Jomar D.', program: 'Business in Korea',
    quote_ko: '온라인이지만 한국 학생들과 실제로 프로젝트를 했어요. 그게 제일 컸습니다.',
    quote_en: "It's online, but I worked on real projects with Korean students. That made the difference." },
  { tag: 'Peru', tag_color: '#248737', name: 'Sofía M.', program: 'Digital Media',
    quote_ko: '처음엔 영어가 걱정이었는데, 자막이랑 멘토 덕분에 따라갈 수 있었어요.',
    quote_en: 'I was worried about my English, but captions and a mentor got me through.' },
];

window.NEWS = [
  { tag: 'WOSM', tag_color: '#6B2DBE', date: '2025.03.18', title_ko: 'APR 스카우트 컨퍼런스에서 DreamPath 정식 소개', title_en: 'DreamPath presented at APR Scout Conference' },
  { tag: 'Korea', tag_color: '#FF5655', date: '2025.02.24', title_ko: 'CUFS와 첫 파트너십 MOU 체결', title_en: 'First partnership MOU signed with CUFS' },
  { tag: '사람들', tag_color: '#248737', date: '2025.01.30', title_ko: '첫 코호트 지원자 인터뷰: 12개국 40명', title_en: 'First cohort interviews: 40 applicants, 12 countries' },
  { tag: 'APR', tag_color: '#0094B4', date: '2024.12.12', title_ko: '아시아-태평양 지역 NSO 대표단 미팅', title_en: 'Asia-Pacific NSO leadership meeting' },
];

window.FAQ = [
  { q_ko: '누가 지원할 수 있나요?', q_en: 'Who can apply?',
    a_ko: '각 국가 스카우트 조직(NSO)에서 활동 중이거나 추천받은 청년이면 지원할 수 있습니다. 나이 기준은 프로그램마다 다릅니다.',
    a_en: 'Any youth active in, or nominated by, their National Scout Organization can apply. Age requirements vary by program.' },
  { q_ko: '영어를 못해도 괜찮나요?', q_en: 'Do I need English?',
    a_ko: '일부 프로그램은 한국어 기본 과정을 포함합니다. 영어/한국어 기초 수준만 있어도 시작할 수 있습니다.',
    a_en: 'Some programs include a Korean basics track. Basic English or Korean is enough to start.' },
  { q_ko: '비용은 얼마인가요?', q_en: 'How much does it cost?',
    a_ko: '마이크로디그리는 파트너 기관의 장학 지원이 있으며, 학생 부담은 최소화됩니다. 프로그램별 상세 비용은 프로그램 페이지에서 확인하세요.',
    a_en: 'Micro-degrees include scholarship support from partner institutions; learner cost is minimized. See each program page for details.' },
  { q_ko: '한국에 가야 하나요?', q_en: 'Do I have to come to Korea?',
    a_ko: '모든 프로그램은 100% 온라인입니다. 선택적으로 단기 방문 프로그램이 있을 수 있습니다.',
    a_en: 'All programs are 100% online. Optional short-term visit programs may be offered.' },
  { q_ko: 'DreamPath와 CUFS의 관계는?', q_en: 'What is the relationship between DreamPath and CUFS?',
    a_ko: 'DreamPath TF는 CUFS와 독립된 조직입니다. CUFS는 첫 파트너 교육기관이며, 추후 복수 기관으로 확장할 예정입니다.',
    a_en: 'DreamPath TF is independent from CUFS. CUFS is our first partner institution; we plan to expand to multiple institutions.' },
];
